name: Automated API tests

on:
  push:
    paths-ignore:
      - 'web/**'
  pull_request:
    paths-ignore:
      - 'web/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

      - uses: earthly/actions-setup@v1
        with:
          version: 'latest' # or pin to an specific version, e.g. "v0.6.10"

      - name: Earthly version
        run: earthly --version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: actions/checkout@v4

      - name: Run API tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: earthly +api-tests
