name: Build and bundle web app into Owncast
on:
  push:
    branches:
      - develop
    paths:
      - 'web/**'
      - '!**.md'

jobs:
  bundle:
    runs-on: ubuntu-latest
    if: github.repository == 'owncast/owncast'

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

      - name: Bundle web app (next.js build)
        uses: actions/checkout@v3
      - run: build/web/bundleWeb.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          pull: --rebase --autostash
          message: 'Bundle embedded web app'
          add: 'static/web'
