# See https://docs.earthly.dev/ci-integration/vendor-specific-guides/gh-actions-integration
# for details.

name: Build nightly docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: 'latest' # or pin to an specific version, e.g. "v0.6.10"

      - name: Earthly version
        run: earthly --version

      - name: Log into GitHub Container Registry
        env:
          GH_CR_PAT: ${{ secrets.GH_CR_PAT }}
        run: echo "${{ secrets.GH_CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        if: env.GH_CR_PAT != null

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: actions/checkout@v3
      - name: Checkout and build
        if: env.GH_CR_PAT != null
        env:
          GH_CR_PAT: ${{ secrets.GH_CR_PAT }}
        run: cd build/release && ./docker-nightly.sh
