name: Release and upgrade tests

on:
  schedule:
    - cron: '0 */12 * * * '

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

      - uses: earthly/actions-setup@v1
        with:
          version: 'latest'

      - name: Install ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Earthly version
        run: earthly --version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: actions/checkout@v3

      - name: Run release upgrade tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd test/automated/upgrades && ./run.sh
